/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Indication
 * OpenAPI spec version: 0.0.1
 */
export type PostSubscriptionsBody = {
  name: string;
  email: string;
  /** @nullable */
  referrer?: string | null;
};

export type PostSubscriptions201 = {
  subscriberId: string;
};

export type GetInviteSubscriberId302 = typeof GetInviteSubscriberId302[keyof typeof GetInviteSubscriberId302] | null;


export const GetInviteSubscriberId302 = {
  null: 'null',
} as const;

export type GetSubscribersSubscriberIdRankingClicks200 = {
  count: number;
};

export type GetSubscribersSubscriberIdRankingCount200 = {
  count: number;
};

export type GetSubscribersSubscriberIdRankingPosition200 = {
  /** @nullable */
  position: number | null;
};

export type GetRanking200RankingItem = {
  id: string;
  name: string;
  score: number;
};

export type GetRanking200 = {
  ranking: GetRanking200RankingItem[];
};

export const getPostSubscriptionsUrl = () => {




  return `http://localhost:3333/subscriptions`
}

/**
 * @summary Subscribes someone to the event
 */
export const postSubscriptions = async (postSubscriptionsBody: PostSubscriptionsBody, options?: RequestInit): Promise<PostSubscriptions201> => {

  const res = await fetch(getPostSubscriptionsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postSubscriptionsBody,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PostSubscriptions201 = body ? JSON.parse(body) : {}
  return data
}



export const getGetInviteSubscriberIdUrl = (subscriberId: string,) => {




  return `http://localhost:3333/invite/${subscriberId}`
}

/**
 * @summary Access invite link and redirects user
 */
export const getInviteSubscriberId = async (subscriberId: string, options?: RequestInit): Promise<unknown> => {

  const res = await fetch(getGetInviteSubscriberIdUrl(subscriberId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: unknown = body ? JSON.parse(body) : {}
  return data
}



export const getGetSubscribersSubscriberIdRankingClicksUrl = (subscriberId: string,) => {




  return `http://localhost:3333/subscribers/${subscriberId}/ranking/clicks`
}

/**
 * @summary Get subscriber invite clicks count
 */
export const getSubscribersSubscriberIdRankingClicks = async (subscriberId: string, options?: RequestInit): Promise<GetSubscribersSubscriberIdRankingClicks200> => {

  const res = await fetch(getGetSubscribersSubscriberIdRankingClicksUrl(subscriberId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetSubscribersSubscriberIdRankingClicks200 = body ? JSON.parse(body) : {}
  return data
}



export const getGetSubscribersSubscriberIdRankingCountUrl = (subscriberId: string,) => {




  return `http://localhost:3333/subscribers/${subscriberId}/ranking/count`
}

/**
 * @summary Get subscriber invites count
 */
export const getSubscribersSubscriberIdRankingCount = async (subscriberId: string, options?: RequestInit): Promise<GetSubscribersSubscriberIdRankingCount200> => {

  const res = await fetch(getGetSubscribersSubscriberIdRankingCountUrl(subscriberId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetSubscribersSubscriberIdRankingCount200 = body ? JSON.parse(body) : {}
  return data
}



export const getGetSubscribersSubscriberIdRankingPositionUrl = (subscriberId: string,) => {




  return `http://localhost:3333/subscribers/${subscriberId}/ranking/position`
}

/**
 * @summary Get subscriber ranking position
 */
export const getSubscribersSubscriberIdRankingPosition = async (subscriberId: string, options?: RequestInit): Promise<GetSubscribersSubscriberIdRankingPosition200> => {

  const res = await fetch(getGetSubscribersSubscriberIdRankingPositionUrl(subscriberId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetSubscribersSubscriberIdRankingPosition200 = body ? JSON.parse(body) : {}
  return data
}



export const getGetRankingUrl = () => {




  return `http://localhost:3333/ranking`
}

/**
 * @summary Get ranking
 */
export const getRanking = async ( options?: RequestInit): Promise<GetRanking200> => {

  const res = await fetch(getGetRankingUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: GetRanking200 = body ? JSON.parse(body) : {}
  return data
}
